package com.example.mygrevocabapp;

import java.util.ArrayList;

public class VocabData {

    public static ArrayList<String[]> getVocabList() {
        ArrayList<String[]> vocabList = new ArrayList<>();


        vocabList.add(new String[]{"Abound(uh-bound)", "to exist in very large numbers, to be plentiful and easy to find"});
        vocabList.add(new String[]{"Adulterate(uh-duhl-tuh-reyt)", "to make something impure or weaker by adding another substance of lower quality"});
        vocabList.add(new String[]{"Abate(uh-beyt)", "to become less strong or intense, to reduce in force or amount"});
        vocabList.add(new String[]{"Abstain(ab-steyn)", "to choose not to do something, especially something you enjoy, often for moral or health reasons"});
        vocabList.add(new String[]{"Aloof(uh-loof)", "not friendly or willing to take part in things, keeping emotional distance from others"});
        vocabList.add(new String[]{"Admonish(ad-mon-ish)", "to warn someone firmly about their behavior, or to give friendly advice about what to do"});
        vocabList.add(new String[]{"Amorphous(uh-mawr-fuhs)", "having no definite shape or form, not clearly organized or structured"});
        vocabList.add(new String[]{"Advocate(ad-vuh-keyt)", "to publicly support or recommend a particular cause or policy"});
        vocabList.add(new String[]{"Abjure(ab-joor)", "to formally reject or give up a belief, claim, or course of action"});
        vocabList.add(new String[]{"Approbation(ap-ruh-bey-shuhn)", "official approval or praise for something, showing you agree with it"});
        vocabList.add(new String[]{"Clangor(klan-ger)", "a continuous loud banging or ringing sound, especially from metal objects hitting each other"});
        vocabList.add(new String[]{"Aesthetic(es-thet-ik)", "relating to beauty and the appreciation of beautiful things, visually pleasing"});
        vocabList.add(new String[]{"Austere(aw-steer)", "very plain and simple in appearance, without any decoration or comfort"});
        vocabList.add(new String[]{"Aggrandize(uh-gran-dahyz)", "to increase the power, status, or wealth of someone or something, often exaggerating importance"});
        vocabList.add(new String[]{"Anomalous(uh-nom-uh-luhs)", "different from what is normal or expected, not fitting into a common pattern"});
        vocabList.add(new String[]{"Cherish(cher-ish)", "to love, value, and care for someone or something deeply over a long time"});
        vocabList.add(new String[]{"Conventional(kuhn-ven-shuh-nl)", "following what is traditional or the way things are normally done"});
        vocabList.add(new String[]{"Affectation(af-ek-tey-shuhn)", "behavior or speech that is not natural and meant to impress others"});
        vocabList.add(new String[]{"Belie(bih-lai)", "to give a false impression of something, to show something is not true"});
        vocabList.add(new String[]{"Alacrity(uh-lak-ri-tee)", "cheerful readiness and quickness to do something without hesitation"});
        vocabList.add(new String[]{"Antipathy(an-tip-uh-thee)", "a strong feeling of dislike or opposition toward someone or something"});
        vocabList.add(new String[]{"Corroborate(kuh-rob-uh-reyt)", "to provide evidence or information that supports a statement, theory, or finding"});
        vocabList.add(new String[]{"Debunk(dee-buhngk)", "to show that a belief or theory is false or exaggerated by exposing the truth"});
        vocabList.add(new String[]{"Alleviate(uh-lee-vee-eyt)", "to make suffering, a problem, or pain less severe or easier to bear"});
        vocabList.add(new String[]{"Capricious(kuh-prish-uhs)", "given to sudden changes in mood or behavior, unpredictable"});
        vocabList.add(new String[]{"Ambivalent(am-biv-uh-luhnt)", "having mixed feelings or contradictory ideas about something or someone"});
        vocabList.add(new String[]{"Arcane(ahr-keyn)", "mysterious and known or understood by only a few people"});
        vocabList.add(new String[]{"Disparate(dis-puh-rit)", "fundamentally different in kind, not allowing comparison"});
        vocabList.add(new String[]{"Diminutive(dih-min-yuh-tiv)", "extremely or unusually small in size or stature"});

        vocabList.add(new String[]{"Analogous(uh-nal-uh-guhs)", "similar in some way to another thing so a comparison can be made"});
        vocabList.add(new String[]{"Cerebral(suh-ree-bruhl)", "intellectual rather than emotional or physical, involving careful thinking"});
        vocabList.add(new String[]{"Ameliorate(uh-mee-lee-uh-reyt)", "to make something bad or unsatisfactory better or more bearable"});
        vocabList.add(new String[]{"Arduous(ar-joo-uhs)", "involving or requiring strenuous effort, difficult and tiring"});
        vocabList.add(new String[]{"Emulate(em-yuh-leyt)", "to match or surpass someone by imitating their good qualities"});
        vocabList.add(new String[]{"Discernible(dih-surn-uh-buhl)", "able to be seen, recognized, or understood with some effort"});
        vocabList.add(new String[]{"Bolster(bohl-ster)", "to support or strengthen something, making it more effective"});
        vocabList.add(new String[]{"Congenial(kun-jee-nee-uhl)", "pleasant and agreeable because of shared interests or qualities"});
        vocabList.add(new String[]{"Amenable(uh-mee-nuh-buhl)", "willing to accept or be influenced by suggestions, open to cooperation"});
        vocabList.add(new String[]{"Artless(ahrt-lis)", "without deception or pretense, natural and sincere in manner"});
        vocabList.add(new String[]{"Enervate(en-er-veyt)", "to drain energy or strength from someone, making them feel weak"});
        vocabList.add(new String[]{"Enigmatic(en-ig-mat-ik)", "mysterious and difficult to understand or interpret"});
        vocabList.add(new String[]{"Chauvinistic(shoh-vuh-nis-tik)", "showing excessive or prejudiced loyalty to a particular group or gender"});
        vocabList.add(new String[]{"Conspicuous(kon-spik-yoo-uhs)", "easily seen or noticed, clearly visible or obvious"});
        vocabList.add(new String[]{"Anachronistic(uh-nak-ruh-nis-tik)", "belonging to a period other than that being portrayed, outdated"});
        vocabList.add(new String[]{"Ascetic(uh-set-ik)", "practicing strict self-discipline and avoiding any pleasures"});
        vocabList.add(new String[]{"Ephemeral(ih-fem-er-uhl)", "lasting for a very short time, fleeting or temporary"});
        vocabList.add(new String[]{"Estranged(ih-streyndjd)", "no longer close or affectionate to someone, alienated"});
        vocabList.add(new String[]{"Connoisseur(kon-uh-sur)", "an expert judge in matters of taste, especially in arts or food"});
        vocabList.add(new String[]{"Cursory(kur-suh-ree)", "done quickly without attention to detail, not thorough"});
        vocabList.add(new String[]{"Audacious(aw-dey-shuhs)", "showing a willingness to take surprisingly bold risks"});
        vocabList.add(new String[]{"Assuage(uh-sweyj)", "to make an unpleasant feeling less intense, to calm or soothe"});
        vocabList.add(new String[]{"Fervid(fur-vid)", "displaying passionate intensity or enthusiasm"});
        vocabList.add(new String[]{"Extravagant(ik-strav-uh-guhnt)", "spending much more than necessary, wasteful or excessive"});
        vocabList.add(new String[]{"Dissemble(dih-sem-buhl)", "to conceal one's true motives or feelings under a false appearance"});
        vocabList.add(new String[]{"Daunting(dawn-ting)", "seeming difficult to deal with in prospect, intimidating"});
        vocabList.add(new String[]{"Avaricious(av-uh-rish-uhs)", "having or showing an extreme greed for wealth or material gain"});
        vocabList.add(new String[]{"Betray(bih-trey)", "to be disloyal to someone who trusts you, or to reveal secrets"});
        vocabList.add(new String[]{"Garrulous(gar-uh-luhs)", "excessively talkative, especially about trivial matters"});
        vocabList.add(new String[]{"Fanciful(fan-si-fuhl)", "overly imaginative or unrealistic, based on fantasy rather than fact"});

        vocabList.add(new String[]{"Dogged(dog-id)", "showing determination to continue despite difficulties"});
        vocabList.add(new String[]{"Deify(dee-uh-fai)", "to worship or regard someone as a god, to idealize excessively"});
        vocabList.add(new String[]{"Banal(buh-nal)", "so lacking in originality as to be obvious and boring"});
        vocabList.add(new String[]{"Bucolic(byoo-kol-ik)", "relating to the pleasant aspects of the countryside and country life"});
        vocabList.add(new String[]{"Incendiary(in-sen-dee-er-ee)", "designed to cause fires, or likely to stir up conflict"});
        vocabList.add(new String[]{"Frivolous(friv-uh-luhs)", "not having any serious purpose or value, silly or trivial"});
        vocabList.add(new String[]{"Dupe(doop)", "to deceive or trick someone into believing something false"});
        vocabList.add(new String[]{"Didactic(dai-dak-tik)", "intended to teach, particularly in having moral instruction"});
        vocabList.add(new String[]{"Benign(bih-nahyn)", "gentle and kindly, or not harmful in effect"});
        vocabList.add(new String[]{"Burgeon(bur-juhn)", "to begin to grow or increase rapidly, to flourish"});
        vocabList.add(new String[]{"Inimical(in-im-i-kuhl)", "tending to obstruct or harm, hostile or unfriendly"});
        vocabList.add(new String[]{"Heterogeneous(het-uh-ruh-jee-nee-uhs)", "diverse in character or content, made up of different kinds"});
        vocabList.add(new String[]{"Empirical(em-pir-i-kuhl)", "based on observation or experience rather than theory"});
        vocabList.add(new String[]{"Disseminate(dih-sem-uh-neyt)", "to spread information, knowledge, etc. widely"});
        vocabList.add(new String[]{"Brazen(brey-zuhn)", "bold and without shame, often in a rude or shocking way"});
        vocabList.add(new String[]{"Cacophonous(ka-kof-uh-nuhs)", "producing a harsh, discordant mixture of sounds"});
        vocabList.add(new String[]{"Intimate(in-tim-it)", "to suggest or hint at something indirectly"});
        vocabList.add(new String[]{"Imperious(im-peer-ee-uhs)", "assuming power or authority without justification, arrogant"});
        vocabList.add(new String[]{"Engender(en-jen-der)", "to produce or cause a particular feeling or situation"});
        vocabList.add(new String[]{"Feasible(fee-zuh-buhl)", "possible to do easily or conveniently, practical"});
        vocabList.add(new String[]{"Calumny(kal-uhm-nee)", "a false statement made to damage someone's reputation"});
        vocabList.add(new String[]{"Canonize(kan-uh-nahyz)", "to officially declare someone a saint, or to regard as important"});
        vocabList.add(new String[]{"Invigorate(in-vig-uh-reyt)", "to give strength or energy to someone or something"});
        vocabList.add(new String[]{"Impertinent(im-pur-tuh-nuhnt)", "not showing proper respect, rude or disrespectful"});
        vocabList.add(new String[]{"Entitled(en-tai-tuhld)", "believing oneself to be inherently deserving of privileges"});
        vocabList.add(new String[]{"Flout(flaut)", "to openly disregard a rule or convention"});
        vocabList.add(new String[]{"Candid(kan-did)", "truthful and straightforward, frank and honest"});
        vocabList.add(new String[]{"Censure(sen-sher)", "to express severe disapproval of someone or something"});
        vocabList.add(new String[]{"Mitigate(mit-i-geyt)", "to make something less severe, serious, or painful"});

        vocabList.add(new String[]{"Invasive(in-vey-siv)", "tending to spread intrusively into other areas"});
        vocabList.add(new String[]{"Pertinacious(pur-tuh-ney-shuhs)", "holding firmly to an opinion or course of action"});
        vocabList.add(new String[]{"Homogeneous(hoh-muh-jee-nee-uhs)", "of the same kind, uniform in composition throughout"});
        vocabList.add(new String[]{"Castigate(kas-ti-geyt)", "to criticize or reprimand someone severely"});
        vocabList.add(new String[]{"Chicanery(shi-key-nuh-ree)", "the use of trickery to achieve a political, financial, or legal purpose"});
        vocabList.add(new String[]{"Obsolete(ob-suh-leet)", "no longer produced or used, out of date"});
        vocabList.add(new String[]{"Irresolute(ir-rez-uh-loot)", "uncertain how to act or proceed, hesitant"});
        vocabList.add(new String[]{"Presumptuous(pri-zuhm-choo-uhs)", "failing to observe the limits of what is permitted"});
        vocabList.add(new String[]{"Humdrum(huhm-druhm)", "lacking excitement or variety, dull and monotonous"});
        vocabList.add(new String[]{"Caustic(kaw-stik)", "sarcastic in a scathing and bitter way"});
        vocabList.add(new String[]{"Coalesce(ko-uh-les)", "to come together to form one mass or whole"});
        vocabList.add(new String[]{"Opaque(oh-peyk)", "not able to be seen through, not transparent"});
        vocabList.add(new String[]{"Laudable(law-duh-buhl)", "deserving praise and commendation"});
        vocabList.add(new String[]{"Probity(proh-bi-tee)", "the quality of having strong moral principles"});
        vocabList.add(new String[]{"Insipid(in-sip-id)", "lacking flavor, vigor, or interest"});
        vocabList.add(new String[]{"Construe(kuhn-stroo)", "to interpret the meaning of something in a particular way"});
        vocabList.add(new String[]{"Cogent(koh-juhnt)", "clear, logical, and convincing"});
        vocabList.add(new String[]{"Paradigmatic(par-uh-daig-mat-ik)", "serving as a typical example or model"});
        vocabList.add(new String[]{"Lax(laks)", "not sufficiently strict, severe, or careful"});
        vocabList.add(new String[]{"Proliferate(pro-lif-uh-reyt)", "to increase rapidly in numbers or spread"});
        vocabList.add(new String[]{"Loquacious(lo-kwey-shuhs)", "tending to talk a great deal, talkative"});
        vocabList.add(new String[]{"Contrite(kon-trait)", "feeling or expressing remorse at having done wrong"});
        vocabList.add(new String[]{"Compelling(kuhm-pel-ing)", "evoking interest or attention in a powerful way"});
        vocabList.add(new String[]{"Pedantic(puh-dan-tik)", "overly concerned with minor details or rules"});
        vocabList.add(new String[]{"Marginalize(mahr-juh-nl-ahyz)", "to treat as insignificant or peripheral"});
        vocabList.add(new String[]{"Specious(spi-shuhs)", "superficially plausible but actually wrong"});
        vocabList.add(new String[]{"Misanthropic(mis-an-throp-ik)", "disliking humankind and avoiding society"});
        vocabList.add(new String[]{"Convoluted(kon-vuh-loo-tid)", "extremely complex and difficult to follow"});
        vocabList.add(new String[]{"Contend(kun-tend)", "to struggle to surmount difficulties"});

        vocabList.add(new String[]{"Placid(plas-id)", "not easily upset or excited, calm and peaceful"});
        vocabList.add(new String[]{"Panache(puh-nash)", "flamboyant confidence of style or manner"});
        vocabList.add(new String[]{"Spurious(spyoor-ee-uhs)", "not being what it purports to be, false"});
        vocabList.add(new String[]{"Misnomer(mis-noh-mer)", "a wrong or inaccurate name or designation"});
        vocabList.add(new String[]{"Covet(kuv-it)", "to yearn to possess something belonging to another"});
        vocabList.add(new String[]{"Copious(koh-pee-uhs)", "abundant in supply or quantity"});
        vocabList.add(new String[]{"Polemical(puh-lem-i-kuhl)", "relating to strong verbal or written attacks"});
        vocabList.add(new String[]{"Plodding(plod-ing)", "slow-moving and unexciting, laborious"});
        vocabList.add(new String[]{"Subjective(suhb-jek-tiv)", "based on personal opinions rather than facts"});
        vocabList.add(new String[]{"Negligent(neg-li-juhnt)", "failing to take proper care in doing something"});
        vocabList.add(new String[]{"Craven(kray-vuhn)", "contemptibly lacking in courage"});
        vocabList.add(new String[]{"Cosmopolitan(koz-muh-pol-i-tuhn)", "familiar with many different countries"});
        vocabList.add(new String[]{"Precipitate(pri-sip-i-teyt)", "to cause something to happen suddenly"});
        vocabList.add(new String[]{"Prosaic(proh-zey-ik)", "lacking poetic beauty, dull"});
        vocabList.add(new String[]{"Subvert(sub-vurt)", "to undermine the power and authority of"});
        vocabList.add(new String[]{"Obsequious(ob-see-kwee-uhs)", "obedient or attentive to an excessive degree"});
        vocabList.add(new String[]{"Decorum(di-kawr-uhm)", "behavior in keeping with good taste"});
        vocabList.add(new String[]{"Deference(def-er-uhns)", "humble submission and respect"});
        vocabList.add(new String[]{"Profundity(proh-fuhn-di-tee)", "great depth of insight or knowledge"});
        vocabList.add(new String[]{"Remedial(ri-mee-dee-uhl)", "intended to correct or improve something"});
        vocabList.add(new String[]{"Timorous(tim-er-uhs)", "showing or suffering from nervousness"});
        vocabList.add(new String[]{"Placate(pley-keyt)", "to make someone less angry or hostile"});
        vocabList.add(new String[]{"Deft(deft)", "neatly skillful and quick in movement"});
        vocabList.add(new String[]{"Desultory(des-uhl-tor-ee)", "lacking a plan, purpose, or enthusiasm"});
        vocabList.add(new String[]{"Prophetic(pro-fet-ik)", "accurately predicting what will happen"});
        vocabList.add(new String[]{"Restive(res-tiv)", "unable to keep still or silent"});
        vocabList.add(new String[]{"Tortuous(tawr-choo-uhs)", "full of twists and turns"});
        vocabList.add(new String[]{"Proclivity(proh-kliv-i-tee)", "a tendency to choose or do something regularly"});
        vocabList.add(new String[]{"Demur(di-mur)", "to raise objections or show reluctance"});
        vocabList.add(new String[]{"Diffident(dif-i-duhnt)", "modest or shy because of lack of self-confidence"});
        vocabList.add(new String[]{"Prudent(proo-dnt)", "acting with or showing care for the future"});
        vocabList.add(new String[]{"Sporadic(spuh-rad-ik)", "occurring at irregular intervals"});
        vocabList.add(new String[]{"Tractable(trak-tuh-buhl)", "easy to control or influence"});
        vocabList.add(new String[]{"Puerile(pyoor-uh-l)", "childishly silly and trivial"});
        vocabList.add(new String[]{"Derivative(di-riv-uh-tiv)", "imitating the work of another artist"});
        vocabList.add(new String[]{"Dilatory(dil-uh-tawr-ee)", "slow to act, intended to cause delay"});
        vocabList.add(new String[]{"Punctilious(puhngk-til-ee-uhs)", "showing great attention to detail"});
        vocabList.add(new String[]{"Stigmatize(stig-muh-taiz)", "to describe or regard as worthy of disgrace"});
        vocabList.add(new String[]{"Transient(tran-shuhnt)", "lasting only for a short time"});

        vocabList.add(new String[]{"Quixotic(kwik-sot-ik)", "exceedingly idealistic"});
        vocabList.add(new String[]{"Desiccate(des-i-kayt)", "remove the moisture from something"});
        vocabList.add(new String[]{"Equivocate(i-kwiv-uh-keyt)", "to use ambiguous language to conceal the truth"});
        vocabList.add(new String[]{"Recondite(re-kon-dait)", "little known, abstruse"});
        vocabList.add(new String[]{"Undermine(un-der-mahyn)", "to erode the base or foundation"});
        vocabList.add(new String[]{"Ubiquitous(yoo-bik-wi-tuhs)", "present, appearing, or found everywhere"});
        vocabList.add(new String[]{"Spendthrift(spend-thrift)", "a person who spends money carelessly"});
        vocabList.add(new String[]{"Diatribe(dai-uh-trahyb)", "a forceful and bitter verbal attack"});
        vocabList.add(new String[]{"Polarize(poh-luh-rahyz)", "to divide into two sharply contrasting groups"});
        vocabList.add(new String[]{"Scrupulous(skroo-pyuh-luhs)", "diligent, thorough, and extremely attentive"});
        vocabList.add(new String[]{"Utterly(uh-ter-lee)", "completely and without qualification"});
        vocabList.add(new String[]{"Underscore(un-der-skawr)", "to emphasize or draw attention to"});
        vocabList.add(new String[]{"Taciturn(tas-i-turn)", "reserved or uncommunicative in speech"});
        vocabList.add(new String[]{"Incredulous(in-krej-uh-luhs)", "unwilling or unable to believe something"});
        vocabList.add(new String[]{"Prodigal(proj-i-guhl)", "spending money or resources recklessly"});
        vocabList.add(new String[]{"Tranquil(trangk-wil)", "free from disturbance, calm"});
        vocabList.add(new String[]{"Weary(weer-ee)", "feeling or showing extreme tiredness"});
        vocabList.add(new String[]{"Venal(vee-nl)", "willing to do dishonest things for money"});
        vocabList.add(new String[]{"Wary(wer-ee)", "feeling or showing caution"});
        vocabList.add(new String[]{"Ingenuous(in-jen-yoo-uhs)", "innocent and unsuspecting"});
        vocabList.add(new String[]{"Verbose(ver-bohs)", "using or containing more words than needed"});
        vocabList.add(new String[]{"Vacillate(vas-i-leyt)", "to alternate between different opinions"});
        vocabList.add(new String[]{"Zealous(zel-uhs)", "having or showing great energy"});
        vocabList.add(new String[]{"Venerate(ven-uh-reyt)", "to regard with great respect"});
        vocabList.add(new String[]{"Appease(uh-peez)", "to bring peace, quiet, or calm to; to soothe"});
        vocabList.add(new String[]{"Arbitrary(ahr-bi-trer-ee)", "based on random choice or personal whim, rather than any reason or system"});
        vocabList.add(new String[]{"Archaic(ahr-key-ik)", "very old or old-fashioned"});
        vocabList.add(new String[]{"Clamorous(kla-muh-ruhs)", "making a loud and confused noise"});
        vocabList.add(new String[]{"Dearth(durth)", "a scarcity or lack of something"});
        vocabList.add(new String[]{"Explicable(ik-spli-kuh-buhl)", "able to be accounted for or understood"});
        vocabList.add(new String[]{"Hyperbole(hai-pur-bo-lee)", "exaggerated statements or claims not meant to be taken literally"});
        vocabList.add(new String[]{"Immutable(i-myoo-tuh-buhl)", "unchanging over time or unable to be changed"});
        vocabList.add(new String[]{"Indefatigable(in-di-fat-i-guh-buhl)", "persisting tirelessly"});
        vocabList.add(new String[]{"Indolent(in-duh-luhnt)", "wanting to avoid activity or exertion; lazy"});
        vocabList.add(new String[]{"Insular(in-suh-ler)", "ignorant of or uninterested in cultures, ideas, or peoples outside one's own experience"});
        vocabList.add(new String[]{"Intransigent(in-tran-si-juhnt)", "unwilling or refusing to change one's views or to agree about something"});
        vocabList.add(new String[]{"Intrepid(in-trep-id)", "fearless; adventurous"});
        vocabList.add(new String[]{"Irreverent(i-rev-er-uhnt)", "showing a lack of respect for people or things that are generally taken seriously"});
        vocabList.add(new String[]{"Loathe(lohth)", "to feel intense dislike or disgust for"});
        vocabList.add(new String[]{"Malign(muh-lahyn)", "evil in nature or effect; malevolent"});
        vocabList.add(new String[]{"Malleable(mal-ee-uh-buhl)", "easily influenced; pliable"});
        vocabList.add(new String[]{"Neophyte(nee-uh-fahyt)", "a person who is new to a subject, skill, or belief"});
        vocabList.add(new String[]{"Plastic(plas-tik)", "able to be molded or shaped"});
        vocabList.add(new String[]{"Platitude(plat-i-tood)", "a remark or statement that may be true but is boring and meaningless because it's been said so many times before"});
        vocabList.add(new String[]{"Prescient(presh-uhnt)", "having or showing knowledge of events before they take place"});
        vocabList.add(new String[]{"Pristine(pris-teen)", "in its original condition; unspoiled"});
        vocabList.add(new String[]{"Reproach(ri-prohch)", "to express disapproval or disappointment"});
        vocabList.add(new String[]{"Robust(ro-buhst)", "strong and healthy; vigorous"});
        vocabList.add(new String[]{"Salubrious(suh-loo-bree-uhs)", "health-giving; healthy"});
        vocabList.add(new String[]{"Sanction(sangk-shuhn)", "a threatened penalty for disobeying a law or rule"});
        vocabList.add(new String[]{"Sedulous(sej-uh-luhs)", "showing dedication and diligence"});
        vocabList.add(new String[]{"Soporific(sop-uh-rif-ik)", "tending to induce drowsiness or sleep"});
        vocabList.add(new String[]{"Stern(sturn)", "serious and unrelenting, especially in the assertion of authority and exercise of discipline"});
        vocabList.add(new String[]{"Tendentious(tuhn-den-shuhs)", "expressing or intending to promote a particular cause or point of view, especially a controversial one"});
        vocabList.add(new String[]{"Accentuate(ak-sen-choo-eyt)", "to emphasize or make more noticeable"});
        vocabList.add(new String[]{"Conjectural(kon-jek-chuh-ruhl)", "based on guesswork rather than knowledge"});
        vocabList.add(new String[]{"Convivial(kon-viv-ee-uhl)", "friendly, lively, and enjoyable"});
        vocabList.add(new String[]{"Decadent(dek-uh-duhnt)", "characterized by moral or cultural decline"});
        vocabList.add(new String[]{"Egregious(i-gree-juhs)", "outstandingly bad or shocking"});

        vocabList.add(new String[]{"Evanescent(ev-uh-nes-uhnt)", "quickly fading or disappearing"});
        vocabList.add(new String[]{"Flamboyant(flam-boi-uhnt)", "bright, colorful, and very noticeable"});
        vocabList.add(new String[]{"Forestall(fawr-stawl)", "to prevent or obstruct by taking action ahead of time"});
        vocabList.add(new String[]{"Gainsay(geyn-sey)", "to deny or contradict"});
        vocabList.add(new String[]{"Galvanize(gal-vuh-nahyz)", "to shock or excite into taking action"});
        vocabList.add(new String[]{"Indiscriminate(in-di-skrim-uh-nit)", "done at random or without careful judgment"});
        vocabList.add(new String[]{"Innocuous(i-nok-yoo-uhs)", "harmless or inoffensive"});
        vocabList.add(new String[]{"Momentary(moh-muhn-ter-ee)", "lasting for a very short time"});
        vocabList.add(new String[]{"Mundane(muhn-deyn)", "lacking interest or excitement; dull"});
        vocabList.add(new String[]{"Nettlesome(net-l-suhm)", "causing annoyance or difficulty"});
        vocabList.add(new String[]{"Nullify(nuhl-uh-fahy)", "to make legally invalid or void"});
        vocabList.add(new String[]{"Obviate(ob-vee-eyt)", "to remove a need or difficulty"});
        vocabList.add(new String[]{"Omnipresent(om-ni-prez-uhnt)", "present everywhere at the same time"});
        vocabList.add(new String[]{"Oust(aust)", "to drive out or expel from a position"});
        vocabList.add(new String[]{"Palpable(pal-puh-buhl)", "able to be touched or felt; tangible"});
        vocabList.add(new String[]{"Perfidy(pur-fi-dee)", "deceitfulness; untrustworthiness"});
        vocabList.add(new String[]{"Profuse(proh-fyoos)", "exuberantly plentiful; abundant"});
        vocabList.add(new String[]{"Pugnacious(puhg-ney-shuhs)", "eager or quick to argue or fight"});
        vocabList.add(new String[]{"Sagacious(suh-gey-shuhs)", "having or showing keen mental discernment"});
        vocabList.add(new String[]{"Sanguine(sang-gwin)", "optimistic or positive, especially in a bad situation"});
        vocabList.add(new String[]{"Scant(skant)", "barely sufficient or adequate"});
        vocabList.add(new String[]{"Skulduggery(skul-dug-uh-ree)", "underhanded or unscrupulous behavior"});
        vocabList.add(new String[]{"Trivial(triv-ee-uhl)", "of little value or importance"});
        vocabList.add(new String[]{"Utilitarian(yoo-til-i-teer-ee-uhn)", "designed to be useful rather than attractive"});
        vocabList.add(new String[]{"Vapid(vap-id)", "offering nothing stimulating or challenging"});
        vocabList.add(new String[]{"Boorish(boor-ish)", "rude and ill-mannered"});
        vocabList.add(new String[]{"Brook(bruk)", "to tolerate or allow something"});
        vocabList.add(new String[]{"Circumspect(sur-kuhm-spekt)", "careful and cautious before acting"});
        vocabList.add(new String[]{"Comity(kom-i-tee)", "friendly and social harmony"});
        vocabList.add(new String[]{"Commensurate(kuh-men-suh-rit)", "equal in size, amount, or degree"});
        vocabList.add(new String[]{"Cordial(kawr-juhl)", "warm and friendly"});
        vocabList.add(new String[]{"Deleterious(del-i-teer-ee-uhs)", "harmful or damaging"});
        vocabList.add(new String[]{"Dichotomy(dahy-kot-uh-mee)", "a clear division between two opposite things"});
        vocabList.add(new String[]{"Edify(ed-uh-fahy)", "to teach or improve someone morally or intellectually"});
        vocabList.add(new String[]{"Elicit(ih-lis-it)", "to draw out a response or reaction"});
        vocabList.add(new String[]{"Erudite(er-yoo-dahyt)", "having or showing deep knowledge"});
        vocabList.add(new String[]{"Fecund(fek-uhnd)", "very fertile or productive"});
        vocabList.add(new String[]{"Feeble(feeb-l)", "weak or lacking strength"});
        vocabList.add(new String[]{"Felicitous(fi-lis-i-tuhs)", "well-chosen and fitting"});
        vocabList.add(new String[]{"Forbear(fawr-bair)", "to hold back from doing something"});
        vocabList.add(new String[]{"Haphazard(hap-haz-erd)", "lacking order or plan; random"});
        vocabList.add(new String[]{"Hodgepodge(hahj-pahj)", "a messy mix of different things"});
        vocabList.add(new String[]{"Impede(im-peed)", "to block or slow down progress"});
        vocabList.add(new String[]{"Impetuous(im-pech-oo-uhs)", "acting quickly without thinking"});
        vocabList.add(new String[]{"Irascible(ih-ras-uh-buhl)", "easily angered"});
        vocabList.add(new String[]{"Mercenary(mur-suh-ner-ee)", "motivated only by money or reward"});
        vocabList.add(new String[]{"Meticulous(muh-tik-yuh-luhs)", "very careful and precise"});
        vocabList.add(new String[]{"Mordant(mawr-dnt)", "biting, sharp, or sarcastic in tone"});
        vocabList.add(new String[]{"Outstrip(out-strip)", "to go faster or do better than something or someone"});
        vocabList.add(new String[]{"Precarious(pri-kair-ee-uhs)", "not secure; risky or dangerous"});
        vocabList.add(new String[]{"Quirky(kwur-kee)", "unusual and interesting in a playful way"});
        vocabList.add(new String[]{"Repudiate(ri-pyoo-dee-eyt)", "to reject or refuse to accept"});
        vocabList.add(new String[]{"Tact(takt)", "skill in saying the right thing without hurting others"});
        vocabList.add(new String[]{"Trifling(trahyf-ling)", "very small or unimportant"});
        vocabList.add(new String[]{"Turbulent(tur-byuh-luhnt)", "disorderly, unstable, or full of conflict"});
        vocabList.add(new String[]{"Acumen(ak-yoo-men)", "the ability to make good quick decisions or judgments"});
        vocabList.add(new String[]{"Antithesis(an-tith-uh-sis)", "the exact opposite of something"});
        vocabList.add(new String[]{"Ascribe(uh-skrahyb)", "to attribute something to a cause or source"});
        vocabList.add(new String[]{"Befuddled(bi-fuhd-uhld)", "confused or unable to think clearly"});
        vocabList.add(new String[]{"Eschew(es-choo)", "to avoid or stay away from something"});
        vocabList.add(new String[]{"Esoteric(es-uh-ter-ik)", "understood by only a small, special group"});
        vocabList.add(new String[]{"Evasive(i-vey-siv)", "avoiding giving a clear answer or escaping"});
        vocabList.add(new String[]{"Exculpate(ek-skuhl-peyt)", "to clear from blame or guilt"});
        vocabList.add(new String[]{"Expedite(ek-spi-dahyt)", "to make something happen faster"});
        vocabList.add(new String[]{"Fastidious(fas-tid-ee-uhs)", "very careful about small details; hard to please"});
        vocabList.add(new String[]{"Feign(feyn)", "to pretend or fake something"});
        vocabList.add(new String[]{"Furtive(fur-tiv)", "secretive and trying not to be noticed"});
        vocabList.add(new String[]{"Hamper(ham-per)", "to slow down or prevent progress"});
        vocabList.add(new String[]{"Indispensable(in-di-spen-suh-buhl)", "absolutely necessary"});
        vocabList.add(new String[]{"Lament(luh-ment)", "to express sadness or regret"});
        vocabList.add(new String[]{"Myopic(mahy-op-ik)", "short-sighted or lacking long-term vision"});
        vocabList.add(new String[]{"Nonchalant(non-shuh-lahnt)", "calm, casual, and not worried"});
        vocabList.add(new String[]{"Partial(par-shuhl)", "showing unfair preference or bias"});
        vocabList.add(new String[]{"Pensive(pen-siv)", "deep in serious or sad thought"});
        vocabList.add(new String[]{"Portend(pawr-tend)", "to be a sign that something (bad) is about to happen"});
        vocabList.add(new String[]{"Provincial(pruh-vin-shuhl)", "narrow-minded or unsophisticated"});
        vocabList.add(new String[]{"Rudimentary(rood-uh-men-ter-ee)", "basic or not fully developed"});
        vocabList.add(new String[]{"Salutary(sal-yuh-ter-ee)", "producing a good or helpful effect"});
        vocabList.add(new String[]{"Sever(sev-er)", "to cut off or break completely"});
        vocabList.add(new String[]{"Slight(slahyt)", "to insult or treat as unimportant"});
        vocabList.add(new String[]{"Somnolent(som-nuh-luhnt)", "very sleepy or drowsy"});
        vocabList.add(new String[]{"Stoic(stoh-ik)", "showing no emotions even in pain or trouble"});
        vocabList.add(new String[]{"Supersede(soo-per-seed)", "to replace something with something newer or better"});
        vocabList.add(new String[]{"Tout(tout)", "to publicly praise or promote something"});
        vocabList.add(new String[]{"Wane(weyn)", "to decrease or become weaker"});

        vocabList.add(new String[]{"Abhor(ab-hor)", "to regard with disgust and hatred"});
        vocabList.add(new String[]{"Boisterous(boi-ster-ous)", "noisy, energetic, and cheerful"});
        vocabList.add(new String[]{"Chivalrous(shiv-ul-rus)", "courteous and gallant, especially towards women"});
        vocabList.add(new String[]{"Churlish(chur-lish)", "rude in a mean-spirited way"});
        vocabList.add(new String[]{"Clandestine(klan-des-tin)", "kept secret or done secretively"});
        vocabList.add(new String[]{"Complacent(kum-play-sent)", "self-satisfied and unaware of potential danger"});
        vocabList.add(new String[]{"Cumbersome(kum-ber-sum)", "large, heavy, and difficult to handle"});
        vocabList.add(new String[]{"Debilitating(dih-bil-i-tay-ting)", "making someone very weak and infirm"});
        vocabList.add(new String[]{"Deliberate(dih-lib-er-it)", "done consciously and on purpose"});
        vocabList.add(new String[]{"Droll(drohl)", "amusing in a quirky or dry way"});
        vocabList.add(new String[]{"Eccentric(ik-sen-trik)", "unconventional and slightly strange"});
        vocabList.add(new String[]{"Fractious(frak-shus)", "irritable and quarrelsome"});
        vocabList.add(new String[]{"Limpid(lim-pid)", "completely clear and transparent"});
        vocabList.add(new String[]{"Mawkish(maw-kish)", "exaggeratedly or falsely sentimental"});
        vocabList.add(new String[]{"Obeisance(oh-bee-sans)", "a gesture of respect, like a bow"});
        vocabList.add(new String[]{"Ostentatious(oss-ten-tay-shus)", "showy and designed to impress"});
        vocabList.add(new String[]{"Panacea(pan-uh-see-uh)", "a cure-all or solution for all problems"});
        vocabList.add(new String[]{"Perfunctory(per-funk-tuh-ree)", "done without care or interest"});
        vocabList.add(new String[]{"Perilous(per-uh-lus)", "full of danger or risk"});
        vocabList.add(new String[]{"Pervasive(per-vay-siv)", "spreading widely throughout an area or group"});
        vocabList.add(new String[]{"Preclude(pri-klood)", "to prevent from happening"});
        vocabList.add(new String[]{"Predilection(pree-duh-lek-shun)", "a special liking for something"});
        vocabList.add(new String[]{"Rapacious(ruh-pay-shus)", "aggressively greedy"});
        vocabList.add(new String[]{"Relish(rel-ish)", "to enjoy greatly"});
        vocabList.add(new String[]{"Satirical(suh-tir-i-kul)", "using humor to mock someone's weaknesses"});
        vocabList.add(new String[]{"Sham(sham)", "a fake or a person who pretends to be something they are not"});
        vocabList.add(new String[]{"Skirt(skurt)", "to go around the edge of something; to avoid dealing with"});
        vocabList.add(new String[]{"Sluggish(slug-ish)", "slow-moving and lacking energy"});
        vocabList.add(new String[]{"Spar-tan(spar-tun)", "austerity; harsh and lacking comfort"});
        vocabList.add(new String[]{"Truculent(truk-yuh-lunt)", "eager to argue; aggressively defiant"});


        vocabList.add(new String[]{"Acrimonious(ak-ri-moh-nee-us)", "angry and bitter"});
        vocabList.add(new String[]{"Belligerent(buh-lij-er-unt)", "hostile and aggressive"});
        vocabList.add(new String[]{"Beneficent(buh-nef-i-sent)", "generous and doing good"});
        vocabList.add(new String[]{"Canny(kan-ee)", "shrewd, especially in money or business"});
        vocabList.add(new String[]{"Cavalier(kav-uh-leer)", "showing a lack of concern"});
        vocabList.add(new String[]{"Distressed(dih-strest)", "suffering from extreme anxiety or pain"});
        vocabList.add(new String[]{"Dwindling(dwin-dling)", "gradually diminishing in size or amount"});
        vocabList.add(new String[]{"Eclipse(ih-klips)", "to overshadow or make less significant"});
        vocabList.add(new String[]{"Encyclopedia(en-sy-kluh-pee-dee-uh)", "a comprehensive reference work"});
        vocabList.add(new String[]{"Exacerbate(ig-zas-er-bayt)", "to make a problem worse"});
        vocabList.add(new String[]{"Exasperated(ig-zas-puh-ray-tid)", "intensely irritated and frustrated"});
        vocabList.add(new String[]{"Fungible(fun-juh-bul)", "mutually interchangeable"});
        vocabList.add(new String[]{"Hackneyed(hak-need)", "overused and unoriginal"});
        vocabList.add(new String[]{"Incongruous(in-kong-groo-us)", "not in harmony with the surroundings"});
        vocabList.add(new String[]{"Interchangeable(in-ter-chayn-juh-bul)", "able to be swapped with each other"});
        vocabList.add(new String[]{"Laconic(luh-kon-ik)", "using very few words"});
        vocabList.add(new String[]{"Lucrative(loo-kruh-tiv)", "producing a great deal of profit"});
        vocabList.add(new String[]{"Magisterial(maj-i-stear-ee-ul)", "domineering and dictatorial"});
        vocabList.add(new String[]{"Onerous(on-er-us)", "involving a great burden; troublesome"});
        vocabList.add(new String[]{"Opprobrium(uh-proh-bree-um)", "harsh criticism or censure"});
        vocabList.add(new String[]{"Parsimonious(par-si-moh-nee-us)", "very unwilling to spend money"});
        vocabList.add(new String[]{"Peripheral(puh-rif-uh-rul)", "of minor importance; on the edge"});
        vocabList.add(new String[]{"Provocative(pruh-vok-uh-tiv)", "causing a strong reaction, often deliberately"});
        vocabList.add(new String[]{"Renounce(ri-nouns)", "to formally give up or reject something"});
        vocabList.add(new String[]{"Tempestuous(tem-pes-choo-us)", "characterized by strong and conflicting emotions"});
        vocabList.add(new String[]{"Tenable(ten-uh-bul)", "able to be defended or maintained"});
        vocabList.add(new String[]{"Transgression(tranz-gresh-un)", "an act that goes against a law or rule"});
        vocabList.add(new String[]{"Urbane(ur-bayn)", "courteous and refined in manner"});
        vocabList.add(new String[]{"Verisimilitude(ver-i-si-mil-i-tood)", "the appearance of being true or real"});
        vocabList.add(new String[]{"Vitiate(vish-ee-ayt)", "to spoil or impair the quality of something"});

        return vocabList;
    }
}
