package com.example.mygrevocabapp;

import java.util.ArrayList;

public class VocabData {

    public static ArrayList<String[]> getVocabList() {
        ArrayList<String[]> vocabList = new ArrayList<>();

        vocabList.add(new String[]{"abound", "to exist in very large numbers, to be plentiful and easy to find"});
        vocabList.add(new String[]{"adulterate", "to make something impure or weaker by adding another substance of lower quality"});
        vocabList.add(new String[]{"abate", "to become less strong or intense, to reduce in force or amount"});
        vocabList.add(new String[]{"abstain", "to choose not to do something, especially something you enjoy, often for moral or health reasons"});
        vocabList.add(new String[]{"aloof", "not friendly or willing to take part in things, keeping emotional distance from others"});
        vocabList.add(new String[]{"admonish", "to warn someone firmly about their behavior, or to give friendly advice about what to do"});
        vocabList.add(new String[]{"amorphous", "having no definite shape or form, not clearly organized or structured"});
        vocabList.add(new String[]{"advocate", "to publicly support or recommend a particular cause or policy"});
        vocabList.add(new String[]{"abjure", "to formally reject or give up a belief, claim, or course of action"});
        vocabList.add(new String[]{"approbation", "official approval or praise for something, showing you agree with it"});
        vocabList.add(new String[]{"clangor", "a continuous loud banging or ringing sound, especially from metal objects hitting each other"});
        vocabList.add(new String[]{"aesthetic", "relating to beauty and the appreciation of beautiful things, visually pleasing"});
        vocabList.add(new String[]{"austere", "very plain and simple in appearance, without any decoration or comfort"});
        vocabList.add(new String[]{"aggrandize", "to increase the power, status, or wealth of someone or something, often exaggerating importance"});
        vocabList.add(new String[]{"anomalous", "different from what is normal or expected, not fitting into a common pattern"});
        vocabList.add(new String[]{"cherish", "to love, value, and care for someone or something deeply over a long time"});
        vocabList.add(new String[]{"conventional", "following what is traditional or the way things are normally done"});
        vocabList.add(new String[]{"affectation", "behavior or speech that is not natural and meant to impress others"});
        vocabList.add(new String[]{"belie", "to give a false impression of something, to show something is not true"});
        vocabList.add(new String[]{"alacrity", "cheerful readiness and quickness to do something without hesitation"});
        vocabList.add(new String[]{"antipathy", "a strong feeling of dislike or opposition toward someone or something"});
        vocabList.add(new String[]{"corroborate", "to provide evidence or information that supports a statement, theory, or finding"});
        vocabList.add(new String[]{"debunk", "to show that a belief or theory is false or exaggerated by exposing the truth"});
        vocabList.add(new String[]{"alleviate", "to make suffering, a problem, or pain less severe or easier to bear"});
        vocabList.add(new String[]{"capricious", "given to sudden changes in mood or behavior, unpredictable"});
        vocabList.add(new String[]{"ambivalent", "having mixed feelings or contradictory ideas about something or someone"});
        vocabList.add(new String[]{"arcane", "mysterious and known or understood by only a few people"});
        vocabList.add(new String[]{"disparate", "fundamentally different in kind, not allowing comparison"});
        vocabList.add(new String[]{"diminutive", "extremely or unusually small in size or stature"});
        vocabList.add(new String[]{"analogous", "similar in some way to another thing so a comparison can be made"});
        vocabList.add(new String[]{"cerebral", "intellectual rather than emotional or physical, involving careful thinking"});
        vocabList.add(new String[]{"ameliorate", "to make something bad or unsatisfactory better or more bearable"});
        vocabList.add(new String[]{"arduous", "involving or requiring strenuous effort, difficult and tiring"});
        vocabList.add(new String[]{"emulate", "to match or surpass someone by imitating their good qualities"});
        vocabList.add(new String[]{"discernible", "able to be seen, recognized, or understood with some effort"});
        vocabList.add(new String[]{"bolster", "to support or strengthen something, making it more effective"});
        vocabList.add(new String[]{"congenial", "pleasant and agreeable because of shared interests or qualities"});
        vocabList.add(new String[]{"amenable", "willing to accept or be influenced by suggestions, open to cooperation"});
        vocabList.add(new String[]{"artless", "without deception or pretense, natural and sincere in manner"});
        vocabList.add(new String[]{"enervate", "to drain energy or strength from someone, making them feel weak"});
        vocabList.add(new String[]{"enigmatic", "mysterious and difficult to understand or interpret"});
        vocabList.add(new String[]{"chauvinistic", "showing excessive or prejudiced loyalty to a particular group or gender"});
        vocabList.add(new String[]{"conspicuous", "easily seen or noticed, clearly visible or obvious"});
        vocabList.add(new String[]{"anachronistic", "belonging to a period other than that being portrayed, outdated"});
        vocabList.add(new String[]{"ascetic", "practicing strict self-discipline and avoiding any pleasures"});
        vocabList.add(new String[]{"ephemeral", "lasting for a very short time, fleeting or temporary"});
        vocabList.add(new String[]{"estranged", "no longer close or affectionate to someone, alienated"});
        vocabList.add(new String[]{"connoisseur", "an expert judge in matters of taste, especially in arts or food"});
        vocabList.add(new String[]{"cursory", "done quickly without attention to detail, not thorough"});
        vocabList.add(new String[]{"audacious", "showing a willingness to take surprisingly bold risks"});
        vocabList.add(new String[]{"assuage", "to make an unpleasant feeling less intense, to calm or soothe"});
        vocabList.add(new String[]{"fervid", "displaying passionate intensity or enthusiasm"});
        vocabList.add(new String[]{"extravagant", "spending much more than necessary, wasteful or excessive"});
        vocabList.add(new String[]{"dissemble", "to conceal one's true motives or feelings under a false appearance"});
        vocabList.add(new String[]{"daunting", "seeming difficult to deal with in prospect, intimidating"});
        vocabList.add(new String[]{"avaricious", "having or showing an extreme greed for wealth or material gain"});
        vocabList.add(new String[]{"betray", "to be disloyal to someone who trusts you, or to reveal secrets"});
        vocabList.add(new String[]{"garrulous", "excessively talkative, especially about trivial matters"});
        vocabList.add(new String[]{"fanciful", "overly imaginative or unrealistic, based on fantasy rather than fact"});
        vocabList.add(new String[]{"dogged", "showing determination to continue despite difficulties"});
        vocabList.add(new String[]{"deify", "to worship or regard someone as a god, to idealize excessively"});
        vocabList.add(new String[]{"banal", "so lacking in originality as to be obvious and boring"});
        vocabList.add(new String[]{"bucolic", "relating to the pleasant aspects of the countryside and country life"});
        vocabList.add(new String[]{"incendiary", "designed to cause fires, or likely to stir up conflict"});
        vocabList.add(new String[]{"frivolous", "not having any serious purpose or value, silly or trivial"});
        vocabList.add(new String[]{"dupe", "to deceive or trick someone into believing something false"});
        vocabList.add(new String[]{"didactic", "intended to teach, particularly in having moral instruction"});
        vocabList.add(new String[]{"benign", "gentle and kindly, or not harmful in effect"});
        vocabList.add(new String[]{"burgeon", "to begin to grow or increase rapidly, to flourish"});
        vocabList.add(new String[]{"inimical", "tending to obstruct or harm, hostile or unfriendly"});
        vocabList.add(new String[]{"heterogeneous", "diverse in character or content, made up of different kinds"});
        vocabList.add(new String[]{"empirical", "based on observation or experience rather than theory"});
        vocabList.add(new String[]{"disseminate", "to spread information, knowledge, etc. widely"});
        vocabList.add(new String[]{"brazen", "bold and without shame, often in a rude or shocking way"});
        vocabList.add(new String[]{"cacophonous", "producing a harsh, discordant mixture of sounds"});
        vocabList.add(new String[]{"intimate", "to suggest or hint at something indirectly"});
        vocabList.add(new String[]{"imperious", "assuming power or authority without justification, arrogant"});
        vocabList.add(new String[]{"engender", "to produce or cause a particular feeling or situation"});
        vocabList.add(new String[]{"feasible", "possible to do easily or conveniently, practical"});
        vocabList.add(new String[]{"calumny", "a false statement made to damage someone's reputation"});
        vocabList.add(new String[]{"canonize", "to officially declare someone a saint, or to regard as important"});
        vocabList.add(new String[]{"invigorate", "to give strength or energy to someone or something"});
        vocabList.add(new String[]{"impertinent", "not showing proper respect, rude or disrespectful"});
        vocabList.add(new String[]{"entitled", "believing oneself to be inherently deserving of privileges"});
        vocabList.add(new String[]{"flout", "to openly disregard a rule or convention"});
        vocabList.add(new String[]{"candid", "truthful and straightforward, frank and honest"});
        vocabList.add(new String[]{"censure", "to express severe disapproval of someone or something"});
        vocabList.add(new String[]{"mitigate", "to make something less severe, serious, or painful"});
        vocabList.add(new String[]{"invasive", "tending to spread intrusively into other areas"});
        vocabList.add(new String[]{"pertinacious", "holding firmly to an opinion or course of action"});
        vocabList.add(new String[]{"homogeneous", "of the same kind, uniform in composition throughout"});
        vocabList.add(new String[]{"castigate", "to criticize or reprimand someone severely"});
        vocabList.add(new String[]{"chicanery", "the use of trickery to achieve a political, financial, or legal purpose"});
        vocabList.add(new String[]{"obsolete", "no longer produced or used, out of date"});
        vocabList.add(new String[]{"irresolute", "uncertain how to act or proceed, hesitant"});
        vocabList.add(new String[]{"presumptuous", "failing to observe the limits of what is permitted"});
        vocabList.add(new String[]{"humdrum", "lacking excitement or variety, dull and monotonous"});
        vocabList.add(new String[]{"caustic", "sarcastic in a scathing and bitter way"});
        vocabList.add(new String[]{"coalesce", "to come together to form one mass or whole"});
        vocabList.add(new String[]{"opaque", "not able to be seen through, not transparent"});
        vocabList.add(new String[]{"laudable", "deserving praise and commendation"});
        vocabList.add(new String[]{"probity", "the quality of having strong moral principles"});
        vocabList.add(new String[]{"insipid", "lacking flavor, vigor, or interest"});
        vocabList.add(new String[]{"construe", "to interpret the meaning of something in a particular way"});
        vocabList.add(new String[]{"cogent", "clear, logical, and convincing"});
        vocabList.add(new String[]{"paradigmatic", "serving as a typical example or model"});
        vocabList.add(new String[]{"lax", "not sufficiently strict, severe, or careful"});
        vocabList.add(new String[]{"proliferate", "to increase rapidly in numbers or spread"});
        vocabList.add(new String[]{"loquacious", "tending to talk a great deal, talkative"});
        vocabList.add(new String[]{"contrite", "feeling or expressing remorse at having done wrong"});
        vocabList.add(new String[]{"compelling", "evoking interest or attention in a powerful way"});
        vocabList.add(new String[]{"pedantic", "overly concerned with minor details or rules"});
        vocabList.add(new String[]{"marginalize", "to treat as insignificant or peripheral"});
        vocabList.add(new String[]{"specious", "superficially plausible but actually wrong"});
        vocabList.add(new String[]{"misanthropic", "disliking humankind and avoiding society"});
        vocabList.add(new String[]{"convoluted", "extremely complex and difficult to follow"});
        vocabList.add(new String[]{"contend", "to struggle to surmount difficulties"});
        vocabList.add(new String[]{"placid", "not easily upset or excited, calm and peaceful"});
        vocabList.add(new String[]{"panache", "flamboyant confidence of style or manner"});
        vocabList.add(new String[]{"spurious", "not being what it purports to be, false"});
        vocabList.add(new String[]{"misnomer", "a wrong or inaccurate name or designation"});
        vocabList.add(new String[]{"covet", "to yearn to possess something belonging to another"});
        vocabList.add(new String[]{"copious", "abundant in supply or quantity"});
        vocabList.add(new String[]{"polemical", "relating to strong verbal or written attacks"});
        vocabList.add(new String[]{"plodding", "slow-moving and unexciting, laborious"});
        vocabList.add(new String[]{"subjective", "based on personal opinions rather than facts"});
        vocabList.add(new String[]{"negligent", "failing to take proper care in doing something"});
        vocabList.add(new String[]{"craven", "contemptibly lacking in courage"});
        vocabList.add(new String[]{"cosmopolitan", "familiar with many different countries"});
        vocabList.add(new String[]{"precipitate", "to cause something to happen suddenly"});
        vocabList.add(new String[]{"prosaic", "lacking poetic beauty, dull"});
        vocabList.add(new String[]{"subvert", "to undermine the power and authority of"});
        vocabList.add(new String[]{"obsequious", "obedient or attentive to an excessive degree"});
        vocabList.add(new String[]{"decorum", "behavior in keeping with good taste"});
        vocabList.add(new String[]{"deference", "humble submission and respect"});
        vocabList.add(new String[]{"profundity", "great depth of insight or knowledge"});
        vocabList.add(new String[]{"remedial", "intended to correct or improve something"});
        vocabList.add(new String[]{"timorous", "showing or suffering from nervousness"});
        vocabList.add(new String[]{"placate", "to make someone less angry or hostile"});
        vocabList.add(new String[]{"deft", "neatly skillful and quick in movement"});
        vocabList.add(new String[]{"desultory", "lacking a plan, purpose, or enthusiasm"});
        vocabList.add(new String[]{"prophetic", "accurately predicting what will happen"});
        vocabList.add(new String[]{"restive", "unable to keep still or silent"});
        vocabList.add(new String[]{"tortuous", "full of twists and turns"});
        vocabList.add(new String[]{"proclivity", "a tendency to choose or do something regularly"});
        vocabList.add(new String[]{"demur", "to raise objections or show reluctance"});
        vocabList.add(new String[]{"diffident", "modest or shy because of lack of self-confidence"});
        vocabList.add(new String[]{"prudent", "acting with or showing care for the future"});
        vocabList.add(new String[]{"sporadic", "occurring at irregular intervals"});
        vocabList.add(new String[]{"tractable", "easy to control or influence"});
        vocabList.add(new String[]{"puerile", "childishly silly and trivial"});
        vocabList.add(new String[]{"derivative", "imitating the work of another artist"});
        vocabList.add(new String[]{"dilatory", "slow to act, intended to cause delay"});
        vocabList.add(new String[]{"punctilious", "showing great attention to detail"});
        vocabList.add(new String[]{"stigmatize", "to describe or regard as worthy of disgrace"});
        vocabList.add(new String[]{"transient", "lasting only for a short time"});
        vocabList.add(new String[]{"quixotic", "exceedingly idealistic"});
        vocabList.add(new String[]{"desiccate", "remove the moisture from something"});
        vocabList.add(new String[]{"equivocate", "to use ambiguous language to conceal the truth"});
        vocabList.add(new String[]{"recondite", "little known, abstruse"});
        vocabList.add(new String[]{"undermine", "to erode the base or foundation"});
        vocabList.add(new String[]{"ubiquitous", "present, appearing, or found everywhere"});
        vocabList.add(new String[]{"spendthrift", "a person who spends money carelessly"});
        vocabList.add(new String[]{"diatribe", "a forceful and bitter verbal attack"});
        vocabList.add(new String[]{"polarize", "to divide into two sharply contrasting groups"});
        vocabList.add(new String[]{"scrupulous", "diligent, thorough, and extremely attentive"});
        vocabList.add(new String[]{"utterly", "completely and without qualification"});
        vocabList.add(new String[]{"underscore", "to emphasize or draw attention to"});
        vocabList.add(new String[]{"taciturn", "reserved or uncommunicative in speech"});
        vocabList.add(new String[]{"incredulous", "unwilling or unable to believe something"});
        vocabList.add(new String[]{"prodigal", "spending money or resources recklessly"});
        vocabList.add(new String[]{"tranquil", "free from disturbance, calm"});
        vocabList.add(new String[]{"weary", "feeling or showing extreme tiredness"});
        vocabList.add(new String[]{"venal", "willing to do dishonest things for money"});
        vocabList.add(new String[]{"wary", "feeling or showing caution"});
        vocabList.add(new String[]{"ingenuous", "innocent and unsuspecting"});
        vocabList.add(new String[]{"verbose", "using or containing more words than needed"});
        vocabList.add(new String[]{"vacillate", "to alternate between different opinions"});
        vocabList.add(new String[]{"zealous", "having or showing great energy"});
        vocabList.add(new String[]{"venerate", "to regard with great respect"});
        vocabList.add(new String[]{"Appease", "to bring peace, quiet, or calm to; to soothe"});
        vocabList.add(new String[]{"Arbitrary", "based on random choice or personal whim, rather than any reason or system"});
        vocabList.add(new String[]{"Archaic", "very old or old-fashioned"});
        vocabList.add(new String[]{"Clamorous", "making a loud and confused noise"});
        vocabList.add(new String[]{"Dearth", "a scarcity or lack of something"});
        vocabList.add(new String[]{"Explicable", "able to be accounted for or understood"});
        vocabList.add(new String[]{"Hyperbole", "exaggerated statements or claims not meant to be taken literally"});
        vocabList.add(new String[]{"Immutable", "unchanging over time or unable to be changed"});
        vocabList.add(new String[]{"Indefatigable", "persisting tirelessly"});
        vocabList.add(new String[]{"Indolent", "wanting to avoid activity or exertion; lazy"});
        vocabList.add(new String[]{"Insular", "ignorant of or uninterested in cultures, ideas, or peoples outside one's own experience"});
        vocabList.add(new String[]{"Intransigent", "unwilling or refusing to change one's views or to agree about something"});
        vocabList.add(new String[]{"Intrepid", "fearless; adventurous"});
        vocabList.add(new String[]{"Irreverent", "showing a lack of respect for people or things that are generally taken seriously"});
        vocabList.add(new String[]{"Loathe", "to feel intense dislike or disgust for"});
        vocabList.add(new String[]{"Malign", "evil in nature or effect; malevolent"});
        vocabList.add(new String[]{"Malleable", "easily influenced; pliable"});
        vocabList.add(new String[]{"Neophyte", "a person who is new to a subject, skill, or belief"});
        vocabList.add(new String[]{"Plastic", "able to be molded or shaped"});
        vocabList.add(new String[]{"Platitude", "a remark or statement that may be true but is boring and meaningless because it's been said so many times before"});
        vocabList.add(new String[]{"Prescient", "having or showing knowledge of events before they take place"});
        vocabList.add(new String[]{"Pristine", "in its original condition; unspoiled"});
        vocabList.add(new String[]{"Reproach", "to express disapproval or disappointment"});
        vocabList.add(new String[]{"Robust", "strong and healthy; vigorous"});
        vocabList.add(new String[]{"Salubrious", "health-giving; healthy"});
        vocabList.add(new String[]{"Sanction", "a threatened penalty for disobeying a law or rule"});
        vocabList.add(new String[]{"Sedulous", "showing dedication and diligence"});
        vocabList.add(new String[]{"Soporific", "tending to induce drowsiness or sleep"});
        vocabList.add(new String[]{"Stern", "serious and unrelenting, especially in the assertion of authority and exercise of discipline"});
        vocabList.add(new String[]{"Tendentious", "expressing or intending to promote a particular cause or point of view, especially a controversial one"});
        vocabList.add(new String[]{"Accentuate", "to emphasize or make more noticeable"});
        vocabList.add(new String[]{"Conjectural", "based on guesswork rather than knowledge"});
        vocabList.add(new String[]{"Convivial", "friendly, lively, and enjoyable"});
        vocabList.add(new String[]{"Decadent", "characterized by moral or cultural decline"});
        vocabList.add(new String[]{"Egregious", "outstandingly bad or shocking"});
        vocabList.add(new String[]{"Evanescent", "quickly fading or disappearing"});
        vocabList.add(new String[]{"Flamboyant", "bright, colorful, and very noticeable"});
        vocabList.add(new String[]{"Forestall", "to prevent or obstruct by taking action ahead of time"});
        vocabList.add(new String[]{"Gainsay", "to deny or contradict"});
        vocabList.add(new String[]{"Galvanize", "to shock or excite into taking action"});
        vocabList.add(new String[]{"Indiscriminate", "done at random or without careful judgment"});
        vocabList.add(new String[]{"Innocuous", "harmless or inoffensive"});
        vocabList.add(new String[]{"Momentary", "lasting for a very short time"});
        vocabList.add(new String[]{"Mundane", "lacking interest or excitement; dull"});
        vocabList.add(new String[]{"Nettlesome", "causing annoyance or difficulty"});
        vocabList.add(new String[]{"Nullify", "to make legally invalid or void"});
        vocabList.add(new String[]{"Obviate", "to remove a need or difficulty"});
        vocabList.add(new String[]{"Omnipresent", "present everywhere at the same time"});
        vocabList.add(new String[]{"Oust", "to drive out or expel from a position"});
        vocabList.add(new String[]{"Palpable", "able to be touched or felt; tangible"});
        vocabList.add(new String[]{"Perfidy", "deceitfulness; untrustworthiness"});
        vocabList.add(new String[]{"Profuse", "exuberantly plentiful; abundant"});
        vocabList.add(new String[]{"Pugnacious", "eager or quick to argue or fight"});
        vocabList.add(new String[]{"Sagacious", "having or showing keen mental discernment"});
        vocabList.add(new String[]{"Sanguine", "optimistic or positive, especially in a bad situation"});
        vocabList.add(new String[]{"Scant", "barely sufficient or adequate"});
        vocabList.add(new String[]{"Skulduggery", "underhanded or unscrupulous behavior"});
        vocabList.add(new String[]{"Trivial", "of little value or importance"});
        vocabList.add(new String[]{"Utilitarian", "designed to be useful rather than attractive"});
        vocabList.add(new String[]{"Vapid", "offering nothing stimulating or challenging"});

        return vocabList;
    }
}
